// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace githubtests {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl PanelTelecomCompanyChooser1;
		
		protected System.Web.UI.WebControls.Label LocationLabel1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl PanelBitcoinAddress1;
		
		protected System.Web.UI.WebControls.TextBox BitcoinAddress1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl PanelDone1;
		
		protected System.Web.UI.WebControls.HyperLink BitcoinUrl1;
	}
}
